from enum import StrEnum


class LLMProvider(StrEnum):
    ATLAS_CLOUD = "ATLAS_CLOUD"
    OPENAI = "OPENAI"
    GEMINI = "GEMINI"
    CLAUDE = "CLAUDE"
    OLLAMA = "OLLAMA"
    BEDROCK = "BEDROCK"
    OPENROUTER = "OPENROUTER"
    AZURE_OPENAI = "AZURE_OPENAI"
