# ===============================
# AI Review configuration file for Azure DevOps + Azure OpenAI
# ===============================

llm:
  # Provider for the Large Language Model - Azure OpenAI
  provider: AZURE_OPENAI

  # LLM metadata configuration for Azure OpenAI
  meta:
    model: gpt-4o               # Base model name (not used in API calls, for pricing only)
    deployment_name: gpt-4o     # Azure OpenAI deployment name
    api_version: 2024-08-01-preview  # Azure OpenAI API version
    max_tokens: 1200            # Maximum tokens for completion
    temperature: 0.3            # Creativity of responses (0 = deterministic)

  # HTTP client configuration for Azure OpenAI
  http_client:
    timeout: 120
    # Azure OpenAI endpoint format: https://<resource-name>.openai.azure.com
    api_url: ${AZURE_OPENAI_ENDPOINT}
    # Azure OpenAI uses api-key header instead of Bearer token
    api_token: ${AZURE_OPENAI_API_KEY}

vcs:
  # Version control system provider - Azure DevOps
  provider: AZURE_DEVOPS

  # Pipeline/PR context for Azure DevOps
  pipeline:
    # Organization name (e.g., "myorg" from https://dev.azure.com/myorg)
    organization: ${AZURE_DEVOPS_ORGANIZATION}
    # Project name (e.g., "MyProject")
    project: ${AZURE_DEVOPS_PROJECT}
    # Repository ID (GUID format)
    repository_id: ${AZURE_DEVOPS_REPOSITORY_ID}
    # Pull Request ID (numeric)
    pull_request_id: ${AZURE_DEVOPS_PULL_REQUEST_ID}

  # HTTP client configuration for Azure DevOps
  http_client:
    timeout: 120
    # Azure DevOps API endpoint format: https://dev.azure.com
    api_url: https://dev.azure.com
    # Personal Access Token (PAT) for authentication
    # Note: Azure DevOps uses Basic auth with base64-encoded PAT
    api_token: ${AZURE_DEVOPS_PAT}

  # Pagination settings for API calls
  pagination:
    per_page: 100
    max_pages: 5

core:
  concurrency: 7

prompt:
  context:
    environment: "production"
    company_name: "My Company"
    ci_pipeline_url: ""
  
  context_placeholder: "<<{value}>>"
  normalize_prompts: true
  
  inline_prompt_files:
    - ./prompts/default_inline.md
  system_inline_prompt_files:
    - ./prompts/default_system_inline.md
  include_inline_system_prompts: true
  
  context_prompt_files:
    - ./prompts/default_context.md
  system_context_prompt_files:
    - ./prompts/default_system_context.md
  include_context_system_prompts: true
  
  summary_prompt_files:
    - ./prompts/default_summary.md
  system_summary_prompt_files:
    - ./prompts/default_system_summary.md
  include_summary_system_prompts: true
  
  inline_reply_prompt_files:
    - ./prompts/default_inline_reply.md
  system_inline_reply_prompt_files:
    - ./prompts/default_system_inline_reply.md
  include_inline_reply_system_prompts: true
  
  summary_reply_prompt_files:
    - ./prompts/default_summary_reply.md
  system_summary_reply_prompt_files:
    - ./prompts/default_system_summary_reply.md
  include_summary_reply_system_prompts: true

review:
  mode: FULL_FILE_DIFF
  dry_run: false
  inline_tag: "#ai-review-inline"
  inline_reply_tag: "#ai-review-inline-reply"
  summary_tag: "#ai-review-summary"
  summary_reply_tag: "#ai-review-summary-reply"
  context_lines: 10
  allow_changes: []
  ignore_changes: []
  review_added_marker: " # added"
  review_removed_marker: " # removed"
  max_inline_comments: null
  max_context_comments: null

logger:
  level: INFO
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {extra[logger_name]} | {message}"

artifacts:
  llm_dir: ./artifacts/llm
  llm_enabled: false

