name: Review

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.12"
        required: false
      review-command:
        type: string
        default: "run"
        required: true
      pull-request-number:
        type: string
        required: true

jobs:
  action:
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install ai-review
        run: pip install .

      - name: Run AI Review
        env:
          AI_REVIEW_CONFIG_FILE_YAML: ./ci/review/config.yaml

          LLM__HTTP_CLIENT__API_TOKEN: ${{ secrets.OPENAI_API_KEY }}
          VCS__HTTP_CLIENT__API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VCS__PIPELINE__OWNER: ${{ github.repository_owner }}
          VCS__PIPELINE__REPO: ${{ github.event.repository.name }}
          VCS__PIPELINE__PULL_NUMBER: ${{ inputs.pull-request-number }}
        run: |
          ai-review show-config
          ai-review ${{ inputs.review-command }}

      - name: Upload AI Review artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-review-llm-artifacts
          path: ./artifacts/llm
          retention-days: 7
    runs-on: ubuntu-latest
