name: 🚀 Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    name: 🧹 lint
    uses: ./.github/workflows/reusable-lint.yml

  test:
    name: 🧪 test
    uses: ./.github/workflows/reusable-test.yml
    needs: lint

  pypi:
    name: 📦 pypi
    uses: ./.github/workflows/reusable-pypi.yml
    needs: test
    secrets: inherit

  docker:
    name: 🐳 docker
    uses: ./.github/workflows/reusable-docker.yml
    needs: pypi
    secrets: inherit
